Repository sap-labs-france/ev-dashboard, pull requests merged in 2021-05, with the labels that each got.

#2393 Dedupe ServerAction
  src/app/types/Server.ts
Labels: clean-up

#2397 Apply security updates.
  README.md
  package-lock.json
Labels: high-prio, security

#2426 transaction history - show invoice number
  src/app/pages/invoices/list/invoices-table-data-source.ts
  src/app/pages/transactions/history/transactions-history-table-data-source.ts
Labels: bug
