Repository sap-labs-france/ev-dashboard, pull requests merged in 2022-01, with the labels that each got.

#2872 Asset auth migration
  src/app/pages/assets/asset/asset-dialog.component.ts
  src/app/pages/assets/asset/asset.component.html
  src/app/pages/assets/asset/asset.component.ts
  src/app/pages/assets/assets.module.ts
  src/app/pages/assets/in-error/assets-in-error-table-data-source.ts
  src/app/pages/assets/list/assets-list-table-data-source.ts
  src/app/pages/cars/car-catalog/car-catalog-dialog.component.ts
  src/app/pages/cars/car-catalogs/car-catalogs-list-table-data-source.ts
  src/app/pages/cars/car/car-dialog.component.ts
  src/app/pages/cars/cars.module.ts
  src/app/pages/cars/cars/cars-list-table-data-source.ts
  src/app/pages/charging-stations/cell-components/charging-stations-transaction-detail-cell.component.ts
  src/app/pages/charging-stations/charging-stations.module.ts
  src/app/pages/charging-stations/details-component/charging-stations-connectors-detail-table-data-source.ts
  src/app/pages/organization/companies/company/company-dialog.component.ts
  src/app/pages/organization/companies/list/companies-list-table-data-source.ts
  src/app/pages/organization/organization.module.ts
  src/app/pages/organization/sites/site/site-dialog.component.ts
  src/app/pages/tags/list/tags-list-table-data-source.ts
  src/app/pages/tags/tag-assign/tag-assign-dialog.component.ts
  src/app/pages/tags/tag/tag-dialog.component.ts
  src/app/pages/tags/tags.module.ts
  src/app/pages/tenants/list/tenants-list-table-data-source.ts
  src/app/pages/tenants/tenant/tenant-dialog.component.ts
  src/app/pages/tenants/tenants.module.ts
  src/app/pages/transactions/history/transactions-history-table-data-source.ts
  src/app/pages/transactions/history/transactions-history.component.ts
  src/app/pages/transactions/in-error/transactions-in-error-table-data-source.ts
  src/app/pages/transactions/in-progress/transactions-in-progress-table-data-source.ts
  src/app/pages/transactions/in-progress/transactions-in-progress.component.ts
  src/app/pages/users/in-error/users-in-error-table-data-source.ts
  src/app/pages/users/in-error/users-in-error.component.ts
  src/app/pages/users/list/users-list-table-data-source.ts
  src/app/pages/users/list/users-list.component.ts
  src/app/pages/users/user/user-dialog.component.ts
  src/app/pages/users/user/user.component.ts
  src/app/pages/users/users.module.ts
  src/app/services/authorization.service.ts
  src/app/services/central-server.service.ts
  src/app/shared/dialogs/dialogs.module.ts
  src/app/shared/dialogs/transaction/transaction-dialog.component.ts
  src/app/shared/table/actions/assets/table-retrieve-asset-consumption-action.ts
  src/app/types/Asset.ts
  src/app/types/Authorization.ts
  src/app/types/DataResult.ts
  src/app/types/HTTPError.ts
  src/assets/i18n/cs.json
  src/assets/i18n/de.json
  src/assets/i18n/en.json
  src/assets/i18n/es.json
  src/assets/i18n/fr.json
  src/assets/i18n/it.json
  src/assets/i18n/pt.json
Labels: enhancement

#2941 dialog - inner HTML - security fix reverted
  src/app/shared/dialogs/confirmation/confirmation-dialog.component.html
Labels: bug

#2847 Pricing restrictions UI
  src/app/pages/settings-integration/pricing/settings-pricing.component.html
  src/app/pages/settings-integration/pricing/settings-pricing.component.ts
  src/app/pages/settings-integration/pricing/simple/settings-simple-pricing.component.html
  src/app/pages/settings-integration/pricing/simple/settings-simple-pricing.component.ts
  src/app/services/central-server.service.ts
  src/app/services/locale.service.ts
  src/app/shared/formatters/app-currency.pipe.ts
  src/app/shared/formatters/app-day.pipe.ts
  src/app/shared/formatters/app-pricing-dimensions-unit.pipe.ts
  src/app/shared/formatters/app-pricing-dimensions.price.pipe.ts
  src/app/shared/formatters/formatters.module.ts
  src/app/shared/pricing-definitions/pricing-definition/pricing-definition.component.html
  src/app/shared/pricing-definitions/pricing-definition/pricing-definition.component.ts
  src/app/shared/pricing-definitions/pricing-definitions-table-data-source.ts
  src/app/shared/pricing-definitions/pricing-definitions.component.html
  src/app/types/Pricing.ts
  src/app/utils/Constants.ts
  src/app/utils/PricingHelpers.ts
  src/assets/i18n/cs.json
  src/assets/i18n/de.json
  src/assets/i18n/en.json
  src/assets/i18n/es.json
  src/assets/i18n/fr.json
  src/assets/i18n/it.json
  src/assets/i18n/pt.json
  src/assets/scss/core/_buttons.scss
  src/assets/scss/views/pricing/pricing.scss
Labels: enhancement

#2962 billing - user sync lazy - no_billing_data useless
  src/app/pages/users/in-error/users-in-error-table-data-source.ts
  src/app/services/central-server.service.ts
  src/app/types/DataResult.ts
  src/app/types/InError.ts
  src/app/types/Server.ts
  src/assets/i18n/cs.json
  src/assets/i18n/de.json
  src/assets/i18n/en.json
  src/assets/i18n/es.json
  src/assets/i18n/fr.json
  src/assets/i18n/it.json
  src/assets/i18n/pt.json
Labels: clean-up
